### ISSUE TITLE
Catalyst 13 TODO

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#584]
- [ ] Attach metadata via `@species` in symbolic interface and DSL.
- [ ] Remove constraint subsystems and handle at the `ReactionSystem` level via filtering `eqs` and `sts`.
- [ ] reorg tutorial and applications organization in docs
- [ ] Double check all tutorials and update / add new ones as appropriate (i.e. constraints and differences in `equations` vs. `reactions` and `states` vs. `species`).
- [ ] update README

This shouldn't actually be that breaking beyond the DSL notation change, *except* for people that are using constraint subsystems (which would be anyone using events). In particular @paulflang and SBMLToolkit will need updates.

**Comment by isaacsas** [comment]
One thing to consider if what the recommended workflow is. Should the examples now use default values and initial conditions via the DSL, making the `@reaction_network` blocks bigger, but getting rid of then having to construct parameter maps all over the place? It seems like maybe we should do this, but then mention this isn't required and one can add them later on.

**Comment by TorkelE** [comment]
My current feeling is that I think parameter maps feel more "natural" in the sense that they appeal more to new users and people that are not familiar with the internals of MTK etc. And in that sense it would be good to keep them as one of the "canon" options. However, I don't want to have any hard opinions until we can discuss it in person properly as I feel I can probably understand your reasoning better then.

**Comment by isaacsas** [comment]
I wasn't planning to deprecated them in either case, but I do think we should decide on what we use as the "standard" approach for all examples.

**Comment by TorkelE** [comment]
Sounds good.

Generally, my current though is that what currently is possible in normal DiffEq (using `f(du,u,p,t)` and similar) should be possible in Catalyst without the user having to engage ModelingToolkit functions. What normally requires ModelingToolkit I think we could leave with ModelingToolkit.

**Comment by isaacsas** [comment]
Catalyst is a ModelingToolkit-based modeling package, and users should be able to use as much ModelingToolkit functionality as possible. More generally, we should try to adhere to ModelingToolkit interfaces to make it easier for users to go between the two. We want to leverage all the stuff getting built for ModelingToolkit and avoid having to put our own versions here.

That said, if the ModelingToolkit interface is not ideal, then we can and should provide extra functionality to make things more convenient. This was the case for specifying initial conditions and parameter values for a system that is already constructed, and where one then had to (in ModelingToolkit) unpack / load all the symbols to build symbol maps.

**Comment by isaacsas** [comment]
It's also the case for the spatial PR, where ModelingToolkit can't handle such systems currently due to the longstanding compilation issues. If/when those get fixed though we should switch to using ModelingToolkit for codegen as much as possible.

**Comment by TorkelE** [comment]
My general concern is that MTK is not very accessible to people new to modelling/programming. I can see why it makes sense for an experienced user that have experience with this stuff and that has had time to dive into how things work. However, I'm afraid that for a more general audience requiring an understanding MTK structures will make it hard for people to engage with the package.

**Comment by isaacsas** [comment]
Can you be more concrete? Is there something you are proposing we should change and rely less on MTK?
