### ISSUE TITLE
Tracker of status of current (and upcoming) PRs

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#710]
Since there are quite a couple of PRs that have accumulated I figured I'd make a list of them to make it easier for you @isaacsas to keep track of their current status. This list is vaguely in order of priority.

### PRs that are done and ready to be merged once reviewed.
- [ ] Base spatial PR with ODE simulations (https://github.com/SciML/Catalyst.jl/pull/644).
- [ ] PEtab tutorial (https://github.com/SciML/Catalyst.jl/pull/701)
- [ ] Support for Spatial SSA simulations (https://github.com/SciML/Catalyst.jl/pull/663)
- [ ] Improved noise scaling implementation (https://github.com/SciML/Catalyst.jl/pull/678)

### PRs that are done, but awaiting changes elsewhere.
- [ ] BifurcationKit extension (https://github.com/SciML/Catalyst.jl/pull/707).

### PRs that are still a work in progress
- [ ] Tutorial for parameter fitting using SciML/Optimization + DiffEqParamEstim (https://github.com/SciML/Catalyst.jl/pull/708)
- [ ]  Structural Identifiability extension (https://github.com/SciML/Catalyst.jl/pull/709)

### Othe PRs
- [ ] SPR fitting tutorial (https://github.com/SciML/Catalyst.jl/pull/704). I have reviewed the first half, and will do the second half once there has been some required updates.
- [ ] Chemistry functionalities documentation (https://github.com/SciML/Catalyst.jl/pull/679). Situation unclear.

### Near future upcoming PRs that have yet to be synched to Catalyst
- [ ] Support for specific matrix forms for Spatial SSAs.
- [ ] Inverse problems introduction doc page.
- [ ] Steady state stability computation function.
- [ ] Homotopy continuation steady state finder internal remake.

Once the spatial PR has been merged, presumably there will be a relatively quick follow-up one modifying various internal stuff according to our discussions.
