### ISSUE TITLE
Catalyst V14 TODO

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#775]
- [x] MTK 9 compatibility and any needed new tests
- [x] Update MTK tests with stuff that has gotten fixed in MTK.
- [x] Add DSL option to control combinatoric_ratelaws
- [x] Remove most mutating API functions (`merge!`, `addspecies!`, etc)?
- [x] finalize new macro fields
- [x] ~~settle how complete will work~~ (settled)
- [x] ~~Should we make conservation law removal of dependent species a non-mutating system transformation, more in line with how MTK does stuff?~~ (will leave as is but perhaps turn on by default for ODE/SDE systems)
- [x] ~~Turn on conservation law removal by default for ODE/Nonlinear/SS systems.~~ will leave off for now
- [x] figure out how we should handle units (do we need more changes?)
- [x] remove all instances where ordering of states or parameters is assumed with regard to initial conditions or parameter values (including across all tests and docs)
- [x] fix mass action jump initialization (MTK)
- [x] fix symbolic stoich tests involving jumps that use MTK internals to get rate/affect functions instead of getting them via `JumpProblem`s. This will allow testing with propoer MTKParameter objects.
- [x] add tests for mixed type parameters and make sure they work/fail appropriately (symbolic integer stoich for ex)
- [x] fix broken jump test with binomials in higher order tests, and broken jump tests in reactionsystem tests
- [x] check how to handle array variables now (stop scalarizing?)
- [x] make sure noise scaling parameters/species/variables get added into systems via the two-argument constructor or the scaling transformation function.
- [x] ensure _all_ tests that are random use StableRNGs.
- [x] Stop testing the v14 dev branch on CI. 
- [x] update docs thoroughly for v14 with regard to existing functionality (i.e. not new tutorials/features)
- [x] update out-of-date stuff in coagulation tutorial
- [x] Improve location of completeness description in docs.
- [x] add migration guide for pre V14 users and make clear how breaking V14 is in the README too
- [x] reenable formatter and format before release (but not till done with PRs...)
- [x] fix https://github.com/SciML/Catalyst.jl/issues/824 and re-enable disabled tests associated with it.
- [x] https://github.com/SciML/Catalyst.jl/issues/825
- [x] https://github.com/SciML/Catalyst.jl/issues/826
- [x] add test for remaking parameters that are functions of other parameters (and updating them in general)
- [x] check whether integer parameters in distributions work
- [x] ~~unitful working?~~ (it doesn't, it will be problematic to sort out)
- [x] DynamicQuantities working? 
- [x] update docs / HISTORY to make clear standard units no longer work.
- [x] ~~fix Latex display of equations with subscripts (as much as possible in Catalyst)~~ (Post V14)
- [x] figure out why plotting jump solution using `saveat` is so slow and update docs accordingly.
- [x] update Catalyst to use "." instead of unicode + as the symbol separator. 

Tracking PRs that are needed for Catalyst 14, including DSL updates. (@TorkelE can you order these in the suggested merge order if you have a chance?)

- [x] https://github.com/SciML/Catalyst.jl/pull/749
- [x] https://github.com/SciML/Catalyst.jl/pull/678
- [x] https://github.com/SciML/Catalyst.jl/pull/784
- [x] https://github.com/SciML/Catalyst.jl/pull/783
- [x] https://github.com/SciML/Catalyst.jl/pull/785
- [x] https://github.com/SciML/Catalyst.jl/pull/786
- [x] https://github.com/SciML/Catalyst.jl/pull/797
- [x] https://github.com/SciML/Catalyst.jl/pull/798
- [x] https://github.com/SciML/Catalyst.jl/pull/761
- [x] https://github.com/SciML/Catalyst.jl/pull/801
- [x] https://github.com/SciML/Catalyst.jl/pull/800
- [x] https://github.com/SciML/Catalyst.jl/pull/823
- [x] https://github.com/SciML/Catalyst.jl/pull/828

There are a number of other doc updates, but most of them seem to be adding new docs/tutorials (instead of updating current docs for MTK9). I think we should get updates for V9 finished and then return to new tutorials.
